### ISSUE TITLE
Back Button Issue

### ISSUE THREAD

**Issue by neerajkhatri-btc** [NishantUpadhyay-BTC/BLISS-Issue-Tracking#176]
Step 1. fill data in Personal Retreat Availability and click check availability
Step 2. select first lodging and click reserve 
Step 3. on Guest Information click back button
Step 4. select last lodging and show pop up and click 'Continue to Existing reservation'
Step 5. on Guest Information click 'continue'
Step 6. on agreements click 'Agree and continue'
Step 7. on Reservation Summary click 'return to reservation'
Step 8. on Guest Information click 'cancel and return to availability'
Step 9. select first lodging and click reserve 
Step 10. on Guest Information click back button

![selection_233](https://cloud.githubusercontent.com/assets/16792762/14629928/ad16176a-0627-11e6-9388-14aae3732f77.png)

**Comment by NishantUpadhyay-BTC** [comment]
Please check this link. This is an issue with Google chrome. Chrome introduced this "feature" in order to avoid users unintentionally duplicating POST actions on forms. But In our case this request is required to display lodging list when user click back button. So we can close this for now as it is not important and may be we can consider in future when we have nothing to address. 
http://superuser.com/questions/341792/disable-confirm-form-resubmission-prompt-on-google-chrome
